version: 2
updates:
  - package-ecosystem: "npm"  # Options: npm, maven, docker, etc.
    directory: "/"          # Location of package manifests
    schedule:
      interval: "weekly"    # Can be "daily", "weekly", or "monthly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"