name: Create PR

on:
  workflow_run:
    workflows: [ "Lint" ]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  
#If this doesn't work, I give up
#Spoiler: It didn't work
#Problem with: The process '/usr/bin/git' failed with exit code 128
#I'm already using PATs, so I don't know what's wrong
#Tried the permissions, but it didn't work
#At this point, I'm assuming it's a Github settings issue I lack the knowledge of
#Needs more investigation but atm I'm just, well, giving up
#Daniel, I apologize!!!

jobs:
  create-pr:
    if: >
      ${{ 
       github.event.workflow_run.conclusion == 'success' &&
       github.ref == 'refs/heads/dev' &&
       !contains(github.event.workflow_run.head_commit.message, 'ci: version bump') 
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Automated Version Bump
        id: bump-version
        uses: phips28/gh-action-bump-version@v11.0.7
        with:
          minor-wording: 'feat'
          major-wording: 'BREAKING'
          patch-wording: 'fix'
          default: 'patch'
          commit-message: 'ci: version bump to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create and push Git tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "v${{ steps.bump-version.outputs.new_version }}" -m "Release v${{ steps.bump-version.outputs.new_version }}"
          git push origin "v${{ steps.bump-version.outputs.new_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          base: "${{ github.event.repository.default_branch == 'master' && 'master' || 'main' }}"
          branch: "auto-pr/dev-to-main-${GITHUB_SHA}"
          delete-branch: true
          title: "chore: version bump to {{version}}"
          body: "Automated PR from dev to main."
          labels: "automated-pr,version-bump"