# name: Autopullbot
# on:
#   push:
#     branches-ignore:
#       - main 
#   workflow_dispatch: 

# jobs:
#   autopull:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4
        
#       - name: Pull Changes
#         run: |
#           git config --global user.email "mauro.dgramos@gmail.com" # Update with your email
#           git config --global user.name "Autopullbot"
#           git fetch origin main
#           git checkout main
#           git merge origin/dev
#           git push origin main

#       - name: Check If Branch is Behind Main
#         run: |
#           echo "Fetching the main branch for comparison..."
#           git fetch origin main
#           BEHIND=$(git rev-list --count HEAD..origin/main)
#           echo "Branch is behind main by $BEHIND commits."
#           if [ "$BEHIND" -le 0 ]; then
#             echo "Branch is up to date with main; no pull request will be created."
#             exit 0
#           fi

#       - name: Create Pull Request
#         run: |
#           echo "Creating a new pull request..."
#           gh pr create \
#             --title "Auto Pull Request - ${{ env.BRANCH_NAME }}" \
#             --body "Auto-generated PR to merge '${{ env.BRANCH_NAME }}' into 'main'" \
#             --base main \
#             --head "${{ env.BRANCH_NAME }}" \
#             --repo "${{ github.repository }}"

name: Create PR

on:
  workflow_run:
    workflows: [ "Lint" ]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  
#If this doesn't work, I give up
#Spoiler: It didn't work
#Problem with: The process '/usr/bin/git' failed with exit code 128
#I'm already using PATs, so I don't know what's wrong
#Tried the permissions, but it didn't work
#At this point, I'm assuming it's a Github settings issue I lack the knowledge of
#Needs more investigation but atm I'm just, well, giving up
#Daniel, I apologize!!!

jobs:
  create-pr:
    if: >-
      ${{ 
        github.event.workflow_run.conclusion == 'success' &&
        github.ref == 'refs/heads/dev' &&
        !contains(github.event.workflow_run.head_commit.message, 'ci: version bump') 
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Automated Version Bump
        id: bump-version
        uses: phips28/gh-action-bump-version@v11.0.7
        with:
          minor-wording: 'feat'
          major-wording: 'BREAKING'
          patch-wording: 'fix'
          default: 'patch'
          commit-message: 'ci: version bump to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create and push Git tag
        run: |
          git config --global user.name "maurograndaoramos"
          git config --global user.email "mauro.dgramos@gmail.com"
          git tag -a "v${{ steps.bump-version.outputs.new_version }}" -m "Release v${{ steps.bump-version.outputs.new_version }}"
          git push origin "v${{ steps.bump-version.outputs.new_version }}"
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  
      - name: Debug Git State
        run: |
          echo "All branches:"
          git branch -a
          echo "Current branch:"
          git branch --show-current
          echo "Latest commit:"
          git log -1 --oneline
          echo "Remote URL:"
          git remote -v
          echo "Git status:"
          git status
          echo "Comparing with main:"
            git log main..HEAD --oneline
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: dev             
          delete-branch: false    
          title: "chore: version bump to ${{ steps.bump-version.outputs.new_version }}"
          body: "Automated PR from dev to main."
          labels: automated-pr,version-bump