name: Automatic PR

on:
  workflow_run:
    workflows: ["Version"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
          
      - name: Get latest commit on main
        id: main-commit
        run: echo "commit=$(git rev-parse origin/main)" >> $GITHUB_OUTPUT
      
      - name: Check for new commits
        id: check-commits
        run: |
          NEW_COMMITS=$(git log origin/main..HEAD --oneline)
          echo "new_commits=$NEW_COMMITS" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.7
        with:
          base: main
          branch: auto-pr/dev-to-main-${{ github.sha }}          
          delete-branch: false    
          title: "chore: merge dev into main"
          body: "Automated PR from dev to main."
          labels: automated-pr