name: Automatic PR

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Fetch all branches
        run: git fetch --all
          
      - name: Debug branches
        run: |
          echo "Current branch:"
          git branch --show-current
          echo "All branches:"
          git branch -a
          echo "Main branch SHA:"
          git rev-parse origin/main
          echo "Dev branch SHA:"
          git rev-parse origin/dev
      
      - name: Check for new commits
        id: check-commits
        run: |
          NEW_COMMITS=$(git log origin/main..origin/dev --oneline)
          echo "Found new commits: $NEW_COMMITS"
          echo "new_commits=$NEW_COMMITS" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Create Pull Request
        if: ${{ steps.check-commits.outputs.new_commits != '' }}
        uses: peter-evans/create-pull-request@v7.0.7
        with:
          base: main
          branch: auto-pr/dev-to-main-${{ github.run_id }}
          delete-branch: true
          title: "chore: merge dev into main"
          body: |
            Automated PR from dev to main.
            
            New commits:
            ${{ steps.check-commits.outputs.new_commits }}
          labels: automated-pr