name: Version

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Automated Version Bump
        id: bump-version
        uses: phips28/gh-action-bump-version@v11.0.7
        with:
          minor-wording: 'feat'
          major-wording: 'BREAKING'
          patch-wording: 'fix'
          default: 'patch'
          commit-message: 'ci: version bump to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create and push Git tag
        run: |
          git config --global user.name "maurograndaoramos"
          git config --global user.email "mauro.dgramos@gmail.com"
          git tag -a "v${{ steps.bump-version.outputs.newTag }}" -m "Release v${{ steps.bump-version.outputs.newTag }}"
          git push origin "v${{ steps.bump-version.outputs.newTag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}